use crate::export::{ExportOptions, Exporter};
use crate::{format_hex_color, ColorPalette, PALETTE_STEPS};
use anyhow::Result;
use serde_json::json;

pub struct DesignTokensExporter;

impl Exporter for DesignTokensExporter {
    fn export(&self, palette: &ColorPalette, options: &ExportOptions) -> Result<String> {
        let mut scale = serde_json::Map::new();

        for step in PALETTE_STEPS {
            if let Some(color) = palette.steps.get(&step) {
                let accessibility = palette.accessibility.steps.get(&step).unwrap();
                scale.insert(
                    step.to_string(),
                    json!({
                        "$value": format_hex_color(color),
                        "$type": "color",
                        "$extensions": {
                            "kanastra": {
                                "contrastOnWhite": format!("{:.2}", accessibility.contrast_against_white),
                                "contrastOnBlack": format!("{:.2}", accessibility.contrast_against_black),
                                "recommendedForeground": accessibility.suggested_foreground.hex(),
                                "rating": accessibility.suggested_foreground.compliance.rating()
                            }
                        }
                    }),
                );
            }
        }

        let token_name = options.name.as_str();
        let output = json!({
            "$description": "Design tokens generated by kanastra-palette-rs",
            "color": {
                token_name: scale,
                "semantic": {
                    token_name: {
                        "$value": format!("{{color.{}.{} }}", token_name, palette.base_step).replace(" }", "}"),
                        "$type": "color",
                        "$description": format!("Default semantic color mapped to step {}", palette.base_step)
                    },
                    format!("on-{}", token_name): {
                        "$value": palette.accessibility.default_foreground.hex(),
                        "$type": "color",
                        "$description": format!(
                            "Recommended foreground for color.{} with {:.2}:1 contrast ({})",
                            token_name,
                            palette.accessibility.default_foreground.contrast_ratio,
                            palette.accessibility.default_foreground.compliance.rating()
                        )
                    }
                }
            },
            "metadata": {
                "generator": "kanastra-palette-rs",
                "format": "design-tokens-v1",
                "algorithm": palette.algorithm.as_str(),
                "defaultStep": palette.base_step
            }
        });

        Ok(serde_json::to_string_pretty(&output)?)
    }
}
